// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWindowSize() {
  return window['go']['main']['App']['CheckWindowSize']();
}

export function GetWindowsPcColors() {
  return window['go']['main']['App']['GetWindowsPcColors']();
}
