// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWindowSize() {
  return window['go']['main']['App']['CheckWindowSize']();
}

export function GetWindowsPcColors() {
  return window['go']['main']['App']['GetWindowsPcColors']();
}

export function MakeMiniWindowSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeMiniWindowSize'](arg1, arg2, arg3);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetWindowAlwaysOnTop'](arg1);
}
