// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWindowSize():Promise<boolean>;

export function GetWindowsPcColors():Promise<string>;
