// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWindowSize() {
  return window['go']['main']['App']['CheckWindowSize']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteCard(arg1) {
  return window['go']['main']['App']['DeleteCard'](arg1);
}

export function GetCards() {
  return window['go']['main']['App']['GetCards']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWindowsPcColors() {
  return window['go']['main']['App']['GetWindowsPcColors']();
}

export function GiveNewSettings(arg1) {
  return window['go']['main']['App']['GiveNewSettings'](arg1);
}

export function MakeMiniWindowSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeMiniWindowSize'](arg1, arg2, arg3);
}

export function SaveCard(arg1) {
  return window['go']['main']['App']['SaveCard'](arg1);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}
